name: refuge_vine
description: Evangelistic Flutter app — Vine & Oil: daily walk with Jesus (John 15; Matt 25).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  flutter_native_timezone_updated: ^2.0.0
  flutter_tts: ^3.8.3
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/de.json
